project           = "wranglr"
region            = "australia-southeast1"
env               = "prod"
app_name          = "ai-invoice-extractor-2"
docker_image_name = "australia-southeast1-docker.pkg.dev/wranglr/prod-ai-invoice-extractor-2/ai-invoice-extractor-2"
